from __future__ import annotations

from pathlib import Path

THEME = {
    # Apple Dark Gray
    "bg": "#1C1C1E",
    "panel": "#1C1C1E",
    "panel_border": "#3A3A3C",
    "card": "#2C2C2E",
    "text": "#F2F2F7",
    "muted": "#AEAEB2",
    # Apple Dark System Colors
    "blue": "#0A84FF",
    "green": "#30D158",
    "indigo": "#5E5CE6",
    "orange": "#FF9F0A",
    "pink": "#FF375F",
    "purple": "#BF5AF2",
    "red": "#FF453A",
    "teal": "#64D2FF",
    "yellow": "#FFD60A",
    # Surface usage
    "danger_bg": "#1C1C1E",
    "danger_text": "#FF453A",
    "danger_border": "#FF453A",
    "warning_bg": "#2C2C2E",
    "warning_text": "#FF9F0A",
    "warning_border": "#FF9F0A",
    "check_bg": "#2C2C2E",
    "check_text": "#64D2FF",
    "check_border": "#636366",
    "safe_bg": "#2C2C2E",
    "safe_text": "#30D158",
    "safe_border": "#30D158",
    "accent": "#0A84FF",
    "accent_hover": "#5E5CE6",
    "accent_active": "#0A84FF",
    "accent_text": "#FFFFFF",
    "button_bg": "#48484A",
    "button_hover": "#636366",
    "button_active": "#8E8E93",
    "button_text": "#F2F2F7",
    "button_border": "#636366",
    "danger_button_bg": "#FF453A",
    "danger_button_hover": "#FF375F",
    "danger_button_active": "#FF453A",
    "danger_button_border": "#FF453A",
    "warn_button_bg": "#FF9F0A",
    "warn_button_hover": "#FFD60A",
    "warn_button_active": "#FF9F0A",
    "warn_button_border": "#FF9F0A",
    "check_button_bg": "#0A84FF",
    "check_button_hover": "#5E5CE6",
    "check_button_active": "#0A84FF",
    "check_button_border": "#0A84FF",
    "output_bg": "#1C1C1E",
    "output_text": "#F2F2F7",
    "focus_ring": "#F2F2F7",
}

DISABLED = {
    "text": "#8E8E93",
    "muted": "#636366",
    "border": "#636366",
    "surface": "#1C1C1E",
    "surface_alt": "#2C2C2E",
    "list_bg": "#1C1C1E",
    "list_text": "#8E8E93",
    "list_border": "#636366",
    "button_bg": "#3A3A3C",
    "button_hover": "#48484A",
    "button_active": "#3A3A3C",
    "button_text": "#8E8E93",
    "notice": "#FFD60A",
}

CANDIDATE_PATHS = [
    {
        "path": "~/.ssh",
        "ja": "SSH秘密鍵と接続設定が入ります。漏えいするとサーバーへ不正接続される危険があります。",
        "en": "Stores SSH private keys and host settings. Exposure may allow unauthorized server access.",
    },
    {
        "path": "~/.aws",
        "ja": "AWS認証情報が含まれることがあります。漏えいするとクラウド資産へ不正操作される危険があります。",
        "en": "May contain AWS credentials. Exposure can allow unauthorized cloud operations.",
    },
    {
        "path": "~/.config/gcloud",
        "ja": "Google Cloud の認証情報が保存されます。漏えいするとプロジェクト操作につながる可能性があります。",
        "en": "Stores Google Cloud credentials. Exposure may allow project-level actions.",
    },
    {
        "path": "~/.gnupg",
        "ja": "GPG秘密鍵や信頼情報が含まれます。漏えいすると署名なりすましや復号リスクがあります。",
        "en": "Contains GPG private keys and trust data. Exposure risks spoofed signatures or decryption.",
    },
    {
        "path": "~/Library/Keychains",
        "ja": "macOSキーチェーン実体です。アカウントや証明書の機密情報が含まれます。",
        "en": "macOS keychain storage. Contains sensitive account and certificate material.",
    },
    {
        "path": "~/.netrc",
        "ja": "CLIで使うログイン情報が平文で入ることがあります。漏えいすると複数サービスへアクセスされます。",
        "en": "Can hold plaintext CLI login credentials. Exposure may grant access to multiple services.",
    },
    {
        "path": "~/.npmrc",
        "ja": "npmトークンが保存されることがあります。漏えいするとパッケージ配布権限を悪用される危険があります。",
        "en": "May include npm tokens. Exposure can let attackers abuse package publishing rights.",
    },
    {
        "path": "~/.docker/config.json",
        "ja": "コンテナレジストリの認証情報が含まれることがあります。漏えいするとイメージの取得や公開を悪用されます。",
        "en": "Can include container registry credentials. Exposure may allow unauthorized pull/push operations.",
    },
    {
        "path": "~/.kube/config",
        "ja": "Kubernetesクラスタの接続情報と認証情報が含まれます。漏えいするとクラスタ操作に繋がります。",
        "en": "Contains Kubernetes cluster endpoints and credentials. Exposure can allow cluster-level operations.",
    },
    {
        "path": "~/.azure",
        "ja": "Azure CLIの認証情報が保存されます。漏えいするとクラウド資産へ不正アクセスされる危険があります。",
        "en": "Stores Azure CLI authentication data. Exposure may enable unauthorized cloud access.",
    },
    {
        "path": "~/.config/gh/hosts.yml",
        "ja": "GitHub CLIのトークン情報が保存されます。漏えいするとリポジトリ操作や設定変更が可能になります。",
        "en": "Stores GitHub CLI token data. Exposure may allow repository actions and settings changes.",
    },
    {
        "path": "~/.git-credentials",
        "ja": "Git資格情報が平文で保存される場合があります。漏えいするとリポジトリへ不正アクセスされます。",
        "en": "May store Git credentials in plain text. Exposure can enable unauthorized repository access.",
    },
    {
        "path": "~/.pypirc",
        "ja": "Pythonパッケージ公開用の認証情報が含まれることがあります。漏えいすると不正な公開操作の危険があります。",
        "en": "May include Python package publishing credentials. Exposure can enable unauthorized package uploads.",
    },
    {
        "path": "~/.zsh_history",
        "ja": "過去コマンド履歴にトークンや秘密URLが残ることがあります。漏えいで横展開されるリスクがあります。",
        "en": "Command history may contain tokens or secret URLs. Exposure can leak credentials and internal endpoints.",
    },
    {
        "path": "~/.bash_history",
        "ja": "bash履歴に機密パラメータが残ることがあります。漏えいすると認証情報の再利用につながります。",
        "en": "Bash history can contain sensitive arguments. Exposure may lead to credential reuse attacks.",
    },
    {
        "path": "~/Library/Application Support/Code/User/globalStorage",
        "ja": "エディタ拡張のセッション情報やトークンが保存されることがあります。漏えいで開発環境情報が流出します。",
        "en": "Editor extensions may store sessions or tokens here. Exposure can leak development environment secrets.",
    },
    {
        "path": "~/Library/Application Support/Google/Chrome/Default/Login Data",
        "ja": "ブラウザ保存ログイン情報のデータベースです。漏えいすると複数サービスへの侵害に繋がります。",
        "en": "Browser-saved login database. Exposure may compromise multiple accounts.",
    },
    {
        "path": "~/Library/Application Support/Google/Chrome/Default/Cookies",
        "ja": "認証済みセッションCookieが含まれます。漏えいするとセッション乗っ取りの危険があります。",
        "en": "Contains authenticated session cookies. Exposure may enable session hijacking.",
    },
    {
        "path": "/etc",
        "ja": "OSやサービスの設定が集まる領域です。誤編集でネットワークや認証に影響します。",
        "en": "Core OS and service configuration files. Wrong edits can impact networking and authentication.",
    },
    {
        "path": "/private/etc/ssh",
        "ja": "SSHサーバー/クライアント設定です。変更すると接続制御や鍵運用に影響します。",
        "en": "SSH server/client configuration. Changes affect access control and key policy.",
    },
    {
        "path": "/private/etc/sudoers.d",
        "ja": "sudo権限設定です。誤変更で権限昇格ポリシーが崩れます。",
        "en": "sudo privilege policy files. Incorrect edits can weaken privilege escalation rules.",
    },
    {
        "path": "/var/db",
        "ja": "システムデータベース領域です。誤変更でOSの整合性に影響する可能性があります。",
        "en": "System database area. Incorrect edits can impact OS integrity.",
    },
    {
        "path": "/Library/LaunchDaemons",
        "ja": "システム起動時に動く常駐ジョブ定義です。誤変更で起動挙動が変わります。",
        "en": "System startup daemon definitions. Bad changes alter boot-time behavior.",
    },
    {
        "path": "/Library/Preferences/SystemConfiguration",
        "ja": "ネットワーク構成などのシステム設定です。誤変更で通信障害の原因になります。",
        "en": "System network configuration. Incorrect edits can cause connectivity issues.",
    },
    {
        "path": "/Library/Application Support/com.apple.TCC",
        "ja": "アプリ権限データベースです。変更するとカメラやマイク等の許可状態に影響します。",
        "en": "App permission database (TCC). Changes affect camera/mic and other privacy grants.",
    },
    {
        "path": "/System",
        "ja": "OS本体の保護領域です。変更対象にしない方が安全です。",
        "en": "Core OS protected area. It is safer to keep this out of modification scope.",
    },
]

PHI = (1 + 5 ** 0.5) / 2
# Approximate golden ratio for left:right layout.
GOLDEN_MAJOR = 1618
GOLDEN_MINOR = 1000
SPACE_XS = 8
SPACE_MD = 10
SPACE_LG = 14
COMPACT_BUTTON_WRAP = 180
SIDE_CONTROL_MIN_WIDTH = 240
FONT_TITLE = 24
FONT_SECTION = 16
FONT_BODY = 13
FONT_META = 12
ONBOARDING_STATE_PATH = Path.home() / ".config" / "secure-agent-locker" / "ui_state.json"
CATEGORY_ORDER = [
    "all",
    "credentials",
    "cloud",
    "system",
    "browser",
    "history",
    "dev",
    "other",
]



TEXTS = {
    "ja": {
        "window_title": "Secure Agent Launcher",
        "app_title": "Secure Agent Launcher",
        "tagline": "禁止リストに登録したパスは、AIの実行から保護されます。",
        "dirty_clean": "保存状態: 最新です",
        "dirty_pending": "保存状態: 未保存の変更があります",
        "protection_label": "保護状態",
        "protection_status_on": "有効（禁止パスを適用中）",
        "protection_status_off": "無効（禁止パスは適用されません）",
        "protection_toggle_on": "保護を有効にする",
        "protection_toggle_off": "保護を無効にする",
        "protection_off_banner": "保護が無効です。禁止パスは現在適用されません。",
        "language_label": "表示言語",
        "lang_ja": "日本語",
        "lang_en": "English",
        "font_label": "文字の大きさ",
        "font_smaller": "A-",
        "font_larger": "A+",
        "blocked_title": "AI アクセス禁止リスト",
        "blocked_desc": "下記のパスはAIがアクセスできません。",
        "quick_add_title": "任意パスを直接追加",
        "quick_add_hint": "ここにパスを貼り付けて Enter でも追加できます。",
        "quick_add_empty": "追加するパスを入力してください。",
        "quick_add_button": "パスを追加",
        "quick_add_pick_button": "選択して追加",
        "remove_button": "選択項目を解除",
        "clear_all_button": "禁止リストを全削除",
        "candidate_title": "パスの追加候補",
        "candidate_desc": "機密情報を含みやすい場所です。選ぶと理由を表示します。",
        "candidate_search_label": "絞り込み",
        "candidate_search_hint": "例: ssh aws chrome",
        "candidate_category_label": "カテゴリ",
        "category_all": "すべて",
        "category_credentials": "認証情報",
        "category_cloud": "クラウド",
        "category_system": "システム",
        "category_browser": "ブラウザ",
        "category_history": "履歴",
        "category_dev": "開発環境",
        "category_other": "その他",
        "candidate_add_button": "選択中の候補を追加",
        "candidate_add_all_button": "表示中の未追加候補をすべて追加",
        "candidate_remove_all_button": "候補から追加した項目を解除",
        "candidate_empty": "候補を選ぶと、理由をここに表示します。",
        "candidate_status_added": "登録済み",
        "candidate_status_pending": "未登録",
        "candidate_item": "{status}  {path}",
        "candidate_detail": "{path}\n分類: {category}\n登録状態: {status}\n実際のパス: {resolved}\n理由: {reason}",
        "candidate_confirm_add_all_title": "候補の一括追加",
        "candidate_confirm_add_all_body": "現在表示中で未追加の候補 {count} 件を禁止パスに追加します。続行しますか？",
        "candidate_confirm_remove_all_title": "候補の一括削除",
        "candidate_confirm_remove_all_body": "すでに追加した候補 {count} 件を禁止パスから削除します。続行しますか？",
        "clear_all_confirm_title": "禁止リストの全削除",
        "clear_all_confirm_body": "禁止リストを {count} 件すべて削除します。続行しますか？",
        "check_title": "禁止リスト内検索",
        "check_desc": "入力したパスが禁止リストに含まれるかを確認します。",
        "check_button": "検索",
        "check_empty": "パスを入力してください。",
        "check_match": "該当します: {path}（一致した禁止パス: {deny}）",
        "check_no_match": "該当なし: {path}",
        "summary_on": "{count} 件のパスを保護中です。",
        "summary_off": "保護は無効です（{count} 件は登録済み）。",
        "mechanism_title": "安全判定の仕組み",
        "mechanism_body": (
            "1) 実行前に、コマンド内のパスを禁止リストと照合します\n"
            "2) 相対パスやシンボリックリンクを解決して判定します\n"
            "3) 一致した場合は、実行前に停止します\n"
            "4) 判定のみモードでは実行せず、判定結果だけ表示します\n"
            "5) 判定結果は監査ログに記録します"
        ),
        "mechanism_note": "このアプリは起動前に判定します。OS全体で強制的に止める仕組みではありません。",
        "guide_title": "エージェント起動手順",
        "guide_body": (
            "1) 実行するコマンドを1行で入力します\n"
            "2) 作業フォルダを確認します\n"
            "3) 左側の禁止リスト設定が反映されることを確認します\n"
            "4) まずは判定のみで安全性を確認します\n"
            "5) 問題なければ起動を実行します"
        ),
        "command_label": "起動するエージェントコマンド",
        "command_hint": "例: codex / claude / gemini（オプション可: codex --model gpt-5）",
        "cwd_label": "作業フォルダ",
        "cwd_hint": "",
        "cwd_pick_button": "選択",
        "target_title": "実行前の確認",
        "target_empty": "コマンドが未入力です。まだ実行されません。",
        "target_body": "コマンド: {command}\n作業フォルダ: {cwd}\n最終実行コマンド: {shell}\nこのアプリが実行するのは上記1行のみです。",
        "execution_title": "エージェント起動",
        "mode_picker_title": "起動モード",
        "preview_button": "判定のみ（起動しない）",
        "execute_button": "起動する",
        "run_action_button_safe": "判定のみを開始",
        "run_action_button_execute": "実行コマンドを生成",
        "run_action_button_protection_off_suffix": "（保護は無効）",
        "generated_command_label": "起動コマンド",
        "generated_command_hint": "生成後、この1行を任意のターミナルに貼り付けて実行します。",
        "generated_command_placeholder": "まだ生成されていません。",
        "generated_command_copy_button": "コピー",
        "timeline_title": "有効になるタイミング",
        "timeline_body": (
            "生成されたコマンド経由でエージェントを起動している場合、"
            "AI アクセス禁止リストのパスは保護されます。"
        ),
        "mode_safe": "現在の設定: 判定のみ（コマンドは実行しません）",
        "mode_execute_requested": "現在の設定: 実行コマンドを生成する",
        "mode_protection_off_suffix": " / 保護は無効",
        "output_label": "状態",
        "policy_location": "設定ファイル: {policy}\n監査ログ: {audit}",
        "next_step_empty_policy": "次の操作: 左側の候補から保護したいパスを追加してください。",
        "next_step_protection_off": "次の操作: 右上のボタンで保護を有効にしてください。",
        "next_step_invalid_cwd": "次の操作: 作業フォルダを実在するフォルダに修正してください。",
        "next_step_no_command": "次の操作: 右側にコマンドを入力して起動準備を完了してください。",
        "next_step_safe": "次の操作: 「判定のみを開始」で安全確認ができます。",
        "next_step_execute": "次の操作: 「実行コマンドを生成」で手動実行用コマンドを作成できます。",
        "run_confirm_title": "起動の確認",
        "run_confirm_body": "左側の禁止リスト設定で検査し、手動実行用コマンドを生成します。続行しますか？",
        "manual_command_title": "実行コマンドを生成しました",
        "manual_command_body": "下の1行を任意のターミナルに貼り付けて実行してください。",
        "manual_command_copy_button": "コピー",
        "manual_command_close_button": "閉じる",
        "error_title": "エラー",
        "error_command_required": "コマンドを入力してください。",
        "error_invalid_cwd": "作業フォルダが見つかりません: {path}",
        "error_cwd_not_directory": "作業フォルダではありません: {path}",
        "error_parse_command": "コマンドを読み取れませんでした: {message}",
        "log_autosaved": "禁止リストを保存して反映しました: {path}",
        "log_external_terminal_started": "外部の Terminal で実行を開始しました: {command}（作業フォルダ: {cwd}）",
        "log_external_terminal_failed": "外部の Terminal を起動できませんでした: {message}",
        "log_protection_on": "保護を有効にしました。",
        "log_protection_off": "保護を無効にしました。",
        "log_candidate_added": "候補を追加しました: {path}",
        "log_candidate_exists": "すでに登録済みです: {path}",
        "log_candidates_added_all": "まだ追加していない候補を {count} 件追加しました。",
        "log_candidates_removed_all": "すでに追加した候補を {count} 件削除しました。",
        "log_candidates_add_nothing": "追加できる候補はありません。",
        "log_candidates_remove_nothing": "削除できる候補はありません。",
        "log_clear_all_done": "禁止リストを {count} 件削除しました。",
        "log_clear_all_nothing": "禁止リストに削除対象がありません。",
        "log_canceled": "実行はキャンセルされました。",
        "log_manual_command": "次の1行をターミナルで実行してください。\n{command}",
        "log_result": "[{reason}] {message}",
        "log_blocked_path": "遮断したパス: {path}",
        "reason_invalid_request": "コマンドが必要です。",
        "reason_blocked_by_policy": "禁止パスに一致したため、実行を停止しました。",
        "reason_dry_run": "判定のみの設定のため、実行していません。",
        "reason_test_mode_block": "テストモードのため実行を拒否しました。",
        "reason_command_not_found": "コマンドが見つかりません。",
        "reason_timeout": "タイムアウトしました。",
        "reason_executed": "コマンドを実行しました。",
        "reason_executed_external_terminal": "対話入力が必要なコマンドのため、外部の Terminal で実行しました。",
        "reason_external_terminal_failed": "外部の Terminal を起動できませんでした。",
        "reason_label_invalid_request": "入力不足",
        "reason_label_blocked_by_policy": "ポリシーで遮断",
        "reason_label_dry_run": "判定のみ",
        "reason_label_test_mode_block": "テストモード",
        "reason_label_command_not_found": "コマンド未検出",
        "reason_label_timeout": "時間切れ",
        "reason_label_executed": "実行完了",
        "reason_label_executed_external_terminal": "外部の Terminal で実行",
        "reason_label_external_terminal_failed": "外部の Terminal 起動失敗",
        "onboarding_title": "はじめに",
        "onboarding_body": (
            "1) 左側の候補から保護したいパスを追加します\n"
            "2) 右側でコマンドと作業フォルダを確認します\n"
            "3) 禁止リストとコマンド内容を確認します\n"
            "4) 起動ボタンでエージェントを実行します"
        ),
    },
    "en": {
        "window_title": "Secure Agent Launcher",
        "app_title": "Secure Agent Launcher",
        "tagline": "Paths in the red list cannot be accessed by AI",
        "dirty_clean": "Save State: Synced",
        "dirty_pending": "Save State: Unsaved Changes",
        "protection_label": "Protection",
        "protection_status_on": "ON (deny paths enforced)",
        "protection_status_off": "OFF (deny paths not enforced)",
        "protection_toggle_on": "Turn Protection ON",
        "protection_toggle_off": "Turn Protection OFF",
        "protection_off_banner": "Protection is OFF. Blocked paths are currently not enforced.",
        "language_label": "Language",
        "lang_ja": "日本語",
        "lang_en": "English",
        "font_label": "Text Size",
        "font_smaller": "A-",
        "font_larger": "A+",
        "blocked_title": "AI Access Deny List",
        "blocked_desc": "Any file/folder here is unreachable for AI.",
        "quick_add_title": "Direct Path Add",
        "quick_add_hint": "Paste a path here and press Enter to add.",
        "quick_add_empty": "Enter a path to add.",
        "quick_add_button": "Add Path",
        "quick_add_pick_button": "Pick And Add",
        "remove_button": "Clear Selected",
        "clear_all_button": "Clear Entire List",
        "candidate_title": "Path Candidates",
        "candidate_desc": "Common high-risk paths. Select one to see why it should be blocked.",
        "candidate_search_label": "Search",
        "candidate_search_hint": "Examples: ssh / aws / chrome",
        "candidate_category_label": "Category",
        "category_all": "All",
        "category_credentials": "Credentials",
        "category_cloud": "Cloud",
        "category_system": "System",
        "category_browser": "Browser",
        "category_history": "History",
        "category_dev": "Dev Environment",
        "category_other": "Other",
        "candidate_add_button": "Add Selected Candidate",
        "candidate_add_all_button": "Add All Visible Not-Added",
        "candidate_remove_all_button": "Unregister Added Candidates",
        "candidate_empty": "Select a candidate path to see its reason.",
        "candidate_status_added": "Added",
        "candidate_status_pending": "Not Added",
        "candidate_item": "{status}  {path}",
        "candidate_detail": "{path}\nCategory: {category}\nStatus: {status}\nResolved path: {resolved}\nWhy block: {reason}",
        "candidate_confirm_add_all_title": "Add Candidate Paths",
        "candidate_confirm_add_all_body": "Add {count} visible not-added candidate paths to blocked paths. Continue?",
        "candidate_confirm_remove_all_title": "Remove Candidate Paths",
        "candidate_confirm_remove_all_body": "Remove {count} added candidate paths from blocked paths. Continue?",
        "clear_all_confirm_title": "Clear Blocked Paths",
        "clear_all_confirm_body": "Remove all {count} paths from blocked paths. Continue?",
        "check_title": "Search In Block List",
        "check_desc": "Find whether a path is included in blocked paths.",
        "check_button": "Search",
        "check_empty": "Enter a path first.",
        "check_match": "Matched: {path} (blocked by: {deny})",
        "check_no_match": "No match: {path}",
        "summary_on": "{count} blocked paths are currently enforced.",
        "summary_off": "Protection is OFF ({count} paths registered but not enforced).",
        "mechanism_title": "How Safety Decision Works",
        "mechanism_body": (
            "1) Before launch, command paths are checked against the blocked list\n"
            "2) Paths are normalized (../ and symlinks are resolved)\n"
            "3) If a match is found, execution is blocked before running\n"
            "4) Check-only mode validates safety and never launches a command\n"
            "5) Every decision is written to the audit log"
        ),
        "mechanism_note": "This build is a launcher guard, not kernel-level enforcement.",
        "guide_title": "Agent Launch Flow",
        "guide_body": (
            "1) Enter exactly one command line to run\n"
            "2) Confirm the working folder\n"
            "3) Confirm blocked paths on the left are ready\n"
            "4) Use Check-Only to validate safety first\n"
            "5) Start launch when the check result looks safe"
        ),
        "command_label": "Agent Command To Launch",
        "command_hint": "Examples: codex / claude / gemini (options are allowed)",
        "cwd_label": "Working Folder",
        "cwd_hint": "",
        "cwd_pick_button": "Browse",
        "target_title": "Execution Preview",
        "target_empty": "No command entered. Nothing will be executed yet.",
        "target_body": "Command: {command}\nWorking folder: {cwd}\nFinal command line: {shell}\nOnly this one command line will be executed.",
        "execution_title": "Agent Launch",
        "mode_picker_title": "Launch Mode",
        "preview_button": "Check Only (No Launch)",
        "execute_button": "Launch",
        "run_action_button_safe": "Start Check Only",
        "run_action_button_execute": "Generate Run Command",
        "run_action_button_protection_off_suffix": "(Protection OFF)",
        "generated_command_label": "Launch command",
        "generated_command_hint": "After generation, paste this one-liner into any terminal and run it.",
        "generated_command_placeholder": "No command generated yet.",
        "generated_command_copy_button": "Copy",
        "timeline_title": "When It Becomes Active",
        "timeline_body": (
            "When the agent is launched via the generated command, "
            "paths in the AI Access Deny List are protected."
        ),
        "mode_safe": "Selected mode: Check Only (command is not executed)",
        "mode_execute_requested": "Selected mode: Generate run command",
        "mode_protection_off_suffix": " / Protection OFF",
        "output_label": "Status",
        "policy_location": "Policy file: {policy}\nAudit log: {audit}",
        "next_step_empty_policy": "Next: add paths to protect from the candidate list on the left.",
        "next_step_protection_off": "Next: turn protection ON using the button at the top right.",
        "next_step_invalid_cwd": "Next: change the working folder to an existing directory.",
        "next_step_no_command": "Next: enter a command on the right to complete launch setup.",
        "next_step_safe": "Next: start Check Only to validate safety before launch.",
        "next_step_execute": "Next: use Generate Run Command to create a one-line command.",
        "run_confirm_title": "Launch Confirmation",
        "run_confirm_body": "Validate this setup against blocked paths and generate a manual run command. Continue?",
        "manual_command_title": "Run Command Generated",
        "manual_command_body": "Run this one-liner in any terminal:",
        "manual_command_copy_button": "Copy",
        "manual_command_close_button": "Close",
        "error_title": "Error",
        "error_command_required": "Command is required.",
        "error_invalid_cwd": "Working folder was not found: {path}",
        "error_cwd_not_directory": "Working folder is not a directory: {path}",
        "error_parse_command": "Failed to parse command: {message}",
        "log_autosaved": "Blocked paths saved and active: {path}",
        "log_external_terminal_started": "Started in external Terminal: {command} (cwd: {cwd})",
        "log_external_terminal_failed": "Failed to start external Terminal: {message}",
        "log_protection_on": "Protection switch is now ON.",
        "log_protection_off": "Protection switch is now OFF.",
        "log_candidate_added": "Candidate path added: {path}",
        "log_candidate_exists": "Already registered: {path}",
        "log_candidates_added_all": "Added {count} candidate paths.",
        "log_candidates_removed_all": "Removed {count} candidate paths.",
        "log_candidates_add_nothing": "No not-added candidates to add.",
        "log_candidates_remove_nothing": "No added candidates to remove.",
        "log_clear_all_done": "Removed {count} blocked paths.",
        "log_clear_all_nothing": "No blocked paths to remove.",
        "log_canceled": "Execution canceled by user.",
        "log_manual_command": "Run this one-liner in your terminal:\n{command}",
        "log_result": "[{reason}] {message}",
        "log_blocked_path": "blocked_path: {path}",
        "reason_invalid_request": "Command is required.",
        "reason_blocked_by_policy": "Blocked because the command matched deny_paths.",
        "reason_dry_run": "Check-only mode. Command was not executed.",
        "reason_test_mode_block": "Execution blocked by test mode.",
        "reason_command_not_found": "Command was not found.",
        "reason_timeout": "Command timed out.",
        "reason_executed": "Command executed.",
        "reason_executed_external_terminal": "TTY-required CLI was launched in external Terminal.",
        "reason_external_terminal_failed": "Failed to start external Terminal.",
        "reason_label_invalid_request": "Invalid Input",
        "reason_label_blocked_by_policy": "Blocked By Policy",
        "reason_label_dry_run": "Check Only",
        "reason_label_test_mode_block": "Test Mode",
        "reason_label_command_not_found": "Command Not Found",
        "reason_label_timeout": "Timeout",
        "reason_label_executed": "Executed",
        "reason_label_executed_external_terminal": "Executed In External Terminal",
        "reason_label_external_terminal_failed": "External Terminal Error",
        "onboarding_title": "Welcome",
        "onboarding_body": (
            "1) Add blocked paths from the candidate list\n"
            "2) Confirm command and working folder on the right\n"
            "3) Confirm blocked paths and command details\n"
            "4) Start the agent with the launch button"
        ),
    },
}

